var source = [
		{"name": "ポークカレー", "price": 505, "default": true},
		{"name": "甘口ポークカレー", "price": 505},
		{"name": "ビーフカレー", "price": 629},
		{"name": "ハッシュドビーフ", "price": 629}
	];
var spiciness = [
		{"name": "甘口", "price": 0},
		{"name": "普通", "price": 0, "default": true},
		{"name": "１辛", "price": 21},
		{"name": "２辛", "price": 42},
		{"name": "３辛", "price": 63},
		{"name": "４辛", "price": 84},
		{"name": "５辛", "price": 105},
		{"name": "６辛", "price": 105},
		{"name": "７辛", "price": 105},
		{"name": "８辛", "price": 105},
		{"name": "９辛", "price": 105},
		{"name": "10辛", "price": 105}
	];
var sweetness = [
		{"name": "普通", "price": 0, "default": true},
		{"name": "１甘", "price": 21},
		{"name": "２甘", "price": 42},
		{"name": "３甘", "price": 63},
		{"name": "４甘", "price": 84},
		{"name": "５甘", "price": 105}
	];
var toppings = [
		{"name":"クリーミータルタルソース", "price":51, "tag":["other"]},
		{"name":"ガーリック", "price":51, "tag":["other"]},
		{"name":"半熟タマゴ", "price":72, "tag":["other"]},
		{"name":"ゆでタマゴ", "price":72, "tag":["other"]},
		{"name":"オクラ山芋", "price":103, "tag":["vegetable"]},
		{"name":"単品ポテト", "price":103, "tag":["vegetable"]},
		{"name":"完熟カットトマト", "price":103, "tag":["vegetable"]},
		{"name":"赤たまねぎのピクルス", "price":81, "limited": "2019-05-29", "tag":["vegetable"]},
		{"name":"赤たまタルタルソース", "price":105, "limited": "2019-05-29", "tag":["vegetable"]},
		{"name":"半熟タマゴタルタルソース", "price":123, "tag":["other"]},
		{"name":"ツナ", "price":103},
		{"name":"コーン", "price":103},
		{"name":"なす", "price":154},
		{"name":"納豆", "price":154},
		{"name":"フィッシュフライ", "price":154},
		{"name":"スクランブルエッグ", "price":154},
		{"name":"たっぷりあさり", "price":185},
		{"name":"エビあさり", "price":195},
		{"name":"チーズ", "price":217},
		{"name":"イカ", "price":206},
		{"name":"クリームコロッケ(カニ入り)", "price":206},
		{"name":"エビにこみ", "price":206},
		{"name":"きのこ", "price":206},
		{"name":"トマトアスパラ", "price":206},
		{"name":"やさい", "price":226},
		{"name":"ほうれん草", "price":226},
		{"name":"チキンにこみ", "price":238},
		{"name":"フライドチキン", "price":238},
		{"name":"ハンバーグ", "price":258},
		{"name":"豚しゃぶ", "price":258},
		{"name":"メンチカツ", "price":258},
		{"name":"ロースカツ", "price":290},
		{"name":"チキンカツ", "price":290},
		{"name":"パリパリチキン", "price":290},
		{"name":"ソーセージ", "price":290},
		{"name":"海の幸", "price":299},
		{"name":"チーズインハンバーグ", "price":308},
		{"name":"ビーフカツ", "price":360},
		{"name":"エビカツ", "price":432},
		{"name":"手仕込ささみカツ", "price":456, "limited": "2019-05-29"},
		{"name":"手仕込ヒレ・ささみカツ", "price":460, "limited": "2019-05-29"},
		{"name":"手仕込ヒレカツ", "price":463, "limited": "2019-05-29"},
		{"name":"手仕込とんかつ", "price":463, "limited": "2019-05-29"}
	];